#CI项目
name: znm2-libWrt-fw4-pw

#CI计划
on:
  # 手动执行
  workflow_dispatch:
  # 默认为utc时间，北京时间需要减去8
  schedule:
    - cron: 0 13 1/7 * *

#CI权限
permissions: write-all

#CI任务
jobs:
  build:
    name: znm2-libWrt-fw4-pw

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/core.yml
    with:
      #编译平台
      TARGET: znm2-libWrt-fw4-pw
      #源码
      REPO_SOURCE: LibWrt
      #源码地址
      REPO_URL: https://github.com/xhixx/openwrt-6.x-breeze
      #源码分支
      REPO_BRANCH: main
      #软件源
      FEEDS_CONF: feeds.conf.default
      #配置文件
      CONFIG_FILE: ./config/libWrt/fw4-pw.config
      #自定义脚本1
      DIY_P1_SH: ./scripts/add_pw_feeds.sh
      #自定义脚本2
      DIY_P2_SH: ./scripts/libWrt/diy-part2.sh
      #预安装脚本
      PRE_INSTALL_SH: ./scripts/pre_install_passwall.sh

